project_id = "stxxtzpttrvpyqhccgme"

[functions.ask-step-question]
verify_jwt = false

[functions.generate-visual-example]
verify_jwt = false

[functions.generate-graph-data]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false
